### ISSUE TITLE
Fix react 18 failing test

### ISSUE THREAD

**Issue by redonkulus** [yahoo/react-stickynode#897]
During React 18 testing [one unit test was not passing](https://github.com/yahoo/react-stickynode/blob/master/tests/unit/Sticky.test.js#L463), further debugging is required. The package was published to unblock users from upgrading to React 18. This bug could break your application!

Issue when running the test:

```bash

  ● Sticky › should release when height gets changed (long Sticky)

    expect(received).toBe(expected) // Object.is equality

    Expected: "translate3d(0,1068px,0)"
    Received: "translate3d(0,-432px,0)"

       97 |     const style = t._style || t.style;
       98 |     expect(style.width).toBe('100px');
    >  99 |     expect(style.transform).toBe('translate3d(0,' + pos + 'px,0)');
          |                             ^
      100 |     expect(style.position).toBe('relative');
      101 |     expect(style.top).toBe('');
      102 | }

      at toBe (tests/unit/Sticky.test.js:99:29)
      at Object.shouldBeReleasedAt (tests/unit/Sticky.test.js:472:9)
```

**Comment by RainGrid** [comment]
The library expects a DOM commit between two setState calls to calc position correct, but React 18 batches those two renders into one commit  
For those who tries to fix dynamic height sticky for example: you can try  
```js
stickyInstance.updateInitialDimension();  
stickyInstance.forceUpdate(() => stickyInstance.update());
```

**Comment by redonkulus** [comment]
@RainGrid do you know the proper way to get access to the instance to force the update?

**Comment by RainGrid** [comment]
> @RainGrid do you know the proper way to get access to the instance to force the update?

const stickyRef = useRef(null);
...
const stickyInstance = stickyRef.current;
...
`<Sticky
        ref={stickyRef} >`
...

**Comment by redonkulus** [comment]
@RainGrid that works for hooks, but sticky-node is a class-based component. We will need a non-hook approach.

**Comment by RainGrid** [comment]
@redonkulus you can call this.forceUpdate(); inside the Sticky component  
Outside you can pass the ref created by React.createRef() https://legacy.reactjs.org/docs/refs-and-the-dom.html#creating-refs. This works somehow, you will get an instance of Sticky with all methods
